### ISSUE TITLE
NetInfo issue

### ISSUE THREAD

**Issue by 0plus1** [ihmpavel/expo-video-player#10]
Hello and thank you for this package, I almost published on myself, you saved me heaps of time!

I just installed it and tried it but I am getting this error:

```
Trying to subscribe to unknown event: "function (_ref) {
        var isConnected = _ref.isConnected;
        setIsOnline(isConnected);
        debug && console.info("User is " + (isConnected ? 'on' : 'off') + "line");
      }"

```

Which leads to this:

```
TypeError: TypeError: NetInfoListener is not a function. (In 'NetInfoListener()', 'NetInfoListener' is an instance of Object)

```

Looks like NetInfo needs linking, so it's not compatible with expo without ejecting?

**Comment by 0plus1** [comment]
I have also tried your new version:
```
yarn add expo-video-player@^1.4.0
```

Which returns a different error but the result is the same.
The culprit is your netinfo requirement, which is ~3.2.1
Expo (without ejecting) is compatible only with:

```
yarn add @react-native-community/netinfo@~2.0.10
// or ..
expo install @react-native-community/netinfo
```

This also means that this package requires expo sdk 33, which is the first one to support netinfo without ejecting.

**Comment by ihmpavel** [comment]
Hi, I have just published version 1.5.0, but that does not matter.

This package requires at least Expo SDK 33, but I recommend using the latest version (eg 34). 

In my example app I am using `@react-native-community/netinfo: ~3.2.1` and Expo 34. Can you please check it if it is working for you?

(I have installed NetInfo library via `expo install @react-native-community/netinfo`, which installs version `~3.2.1`)

Peer (recommended) dependencies for entire library are
```
 "@react-native-community/netinfo": ">=3.2.1",
 "expo": ">=33.0.0",
 "expo-av": ">=5.0.2"
```

**Comment by 0plus1** [comment]
Expo 34 indeed installs netinfo 3.2.1, which means this package is compatible only on expo sdk 34, you should probably state that in the readme.

**Comment by ihmpavel** [comment]
Hi, I have checked everything and unfortunatelly you are right. 

I was expecting, RN 59 on Expo SDK 33 will use `NetInfo` version `~3.*.*` instead of version `~2.*.*`. But I did not test it properly...

Due to this, I will suggest you using version `1.2.0`.
Check it here: https://snack.expo.io/BkUqeimrB

I will definetely update the docs about this. Thank you for your patience.

**Comment by ihmpavel** [comment]
Added docs in #16
