### ISSUE TITLE
Unable to get player working

### ISSUE THREAD

**Issue by SerdarMustafa1** [ihmpavel/expo-video-player#106]
Unable to play any videos.

Receiving error: 'ExceptionsManager.js:126 Error:  Encountered a fatal error during playback: The server is not correctly configured. - The AVPlayerItem instance has failed with the error code -11850 and domain "AVFoundationErrorDomain".'

I tried my own code and your example and receive the same error each time. I also tried different video URLs.

Expect a video to load and play

  Expo CLI 3.16.1 environment info:
    System:
      OS: macOS 10.15
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.14.0 - ~/.nvm/versions/node/v12.14.0/bin/node
      Yarn: 1.16.0 - /usr/local/bin/yarn
      npm: 6.13.4 - ~/.nvm/versions/node/v12.14.0/bin/npm
    IDEs:
      Xcode: /undefined - /usr/bin/xcodebuild
    npmPackages:
      expo: ~36.0.0 => 36.0.2 
      react: ~16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz => 0.61.4 
      react-navigation: ^4.3.3 => 4.3.3 
    npmGlobalPackages:
      expo-cli: 3.16.1

The issue occurs on all devices ad emulators

Any help or advice would be great.

```
import React, { useState } from "react";
import { StyleSheet, Text, View } from "react-native";
import { Video } from "expo-av";
import VideoPlayer from "expo-video-player";

Player = () => {
  const [isPlaying, setIsPlaying] = useState(false);
  return (
    <View style={styles.container}>
      <Text>isPlaying: {JSON.stringify(isPlaying)}</Text>
      <VideoPlayer
        videoProps={{
          width: 250,
          height: 250,
          shouldPlay: true,
          resizeMode: Video.RESIZE_MODE_CONTAIN,
          source: {
            uri: "https://youtu.be/S9VjeIWLnEg"
          }
        }}
        inFullscreen={false}
        playbackCallback={status => {
          if (isPlaying !== status.isPlaying) {
            setIsPlaying(status.isPlaying);
          }
        }}
      />
    </View>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
    paddingTop: 80
  }
});

export default Player;
```

**Comment by ihmpavel** [comment]
Hi, this is video player. The source you are providing is webpage url. 

You need to pass url to video file stored locally or on remote server. (Eg with ending mp4...) 

Please check source: https://docs.expo.io/versions/latest/sdk/video/#props
