### ISSUE TITLE
Unable to attach a Ref to video player.

### ISSUE THREAD

**Issue by JCron245** [ihmpavel/expo-video-player#127]
**Describe the bug**
I am trying to put a ref on the video player so that I can stop/play programatticaly. However it just keeps giving me typescript errors.

**To Reproduce**
In a typescript project try to attach a ref as a property of the VideoPlayer I get:

> Property 'ref' does not exist on type 'IntrinsicAttributes & Pick<Props, "videoProps"> & { children?: null; playIcon?: () => Element; pauseIcon?: () => Element; spinner?: () => Element; ... 21 more ...; showControlsOnLoad?: boolean; }'.ts(2322)

```
<VideoPlayer
        height={isTablet ? 525 : 300}
	inFullscreen={false}
	quickFadeOutDuration={420}
	videoProps={{
		shouldPlay: true,
		resizeMode: 'contain',
		source: {
			uri: videoSource
		},
        }}
        ref={}
	switchToLandscape={fullScreenMode}
	width={screenDimensions.width}
/>
```
I also saw an example somewhere I thought (can't find it now) of someone attaching it in the videoprops object but that also throws an error and looking at the videoprops type interface it is not in there either.

Not sure if this is a bug (more likely I am just not doing something right)

**Expected behavior**
A ref to be assignable to the video player component.

**Additional infofmation:**
 - Type: Real Devices
 - Device: iPhone XS and NVIDIA Shield Tablet
 - OS: iOS13 - Android 7
 - Package version: 1.5.7
 - Expo version: 37
 - Expo CLI version: 3.17.16

**Screenshots** (if applicable)

**Comment by JCron245** [comment]
I found the other place where the ref is being attached via videoProps [https://github.com/ihmpavel/expo-video-player/issues/57](expo-video-player issue 57)

However when I attempt to do it this way I get:
```
Type '{ ref: (v: any) => any; shouldPlay: boolean; resizeMode: string; source: { uri: string; }; }' is not assignable to type 'VideoProps'.
  Object literal may only specify known properties, and 'ref' does not exist in type 'VideoProps'.ts(2322)
```

**Comment by ihmpavel** [comment]
Hi,

there are some issues while using `ref`. 

Right now there are two options (before I look into that in code more deeply).

1) Turn off TypeScript type warnings for `ref` and use like in https://github.com/ihmpavel/expo-video-player/issues/57#issuecomment-583787627
```
<VideoPlayer      
  ...
  videoProps={{
    // @ts-ignore
    ref: v => (video = v)
 }}
/>
```

2) Use `state` to `play/pause`

```
<VideoPlayer      
  ...
  videoProps={{
    shouldPlay,
 }}
/>
...
const [shouldPlay, setShouldPlay] = useState(true)
<TouchableOpacity onPress={() => setShouldPlay(false)}>...</TouchableOpacity>
```

Let me know, if is it working for you. (PRs are also welcome.)

**Comment by JCron245** [comment]
Hello! I gave the first option above a try yesterday with ignoring the TS error but the ref would always be undefined. 
I will try the state way today and post here if I am able to get it to work, thank you for the feedback!

**Comment by JCron245** [comment]
Controlling the video with a state variable is much smoother! However I am still encountering one issue that I was hoping a true `ref` would solve for me.

On my iPhone with VoiceOver enabled if I navigate away from a screen with a playing video it wont stop playing.

`
useEffect( () => {
  // Get Video Source
  setShouldPlay(true);
 // Video begins playing 
  return (): void => {
    // unmount occurs
    setShouldPlay(false); // Setting this to false will usually kill the video, but not if VoiceOver is enabled
    };
}, []);
`
I thought if I had the ref that calling `videoRef.stopAsync()` would maybe work where the unmount seems to be failing?

**Comment by shailu26** [comment]
Is there anyway we can show exit icon?

**Comment by ihmpavel** [comment]
Latest version (1.6.0) has property `videoRef`, feel free to try it! 😀

**Comment by TREFZ** [comment]
@ihmpavel Do you have example using the `videoRef` prop on this component? I'm trying to trigger `presentFullscreenPlayer()` on `switchToLandscape` but I can get the ref to work.
