### ISSUE TITLE
Cannot show poster image

### ISSUE THREAD

**Issue by tanhhkhcndn** [ihmpavel/expo-video-player#150]
Firstly,Thanks for your video player!
i used your expo-video-play, and i add poster props like that
videoProps={{
            shouldPlay: false,
            resizeMode: Video.RESIZE_MODE_COVER,
            source: {
              uri: myurl,
            },
            posterSource: {
              uri: "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/images/BigBuckBunny.jpg"
            },
          }}          
          inFullscreen={false}
          showControlsOnLoad={true}
          showFullscreenButton={true}
          videoBackground='transparent'
          width={widthSize}
          height={heightSize}
but, poster cannot display, i tried to use local image by require("/assets/images/picture.jpg"). but errors that require variable.
and help me how to navigation to new screen when show full screen in video.
Expo sdk 37
Expo AV
thanks

**Comment by ihmpavel** [comment]
Hello,

could you please add `usePoster` to videoProps?

Let me know, if it is working for you.

```
<VideoPlayer
  videoProps={{
    shouldPlay: false,
    resizeMode: Video.RESIZE_MODE_CONTAIN,
    source: {
      uri:  'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    },
    posterSource: {
      uri: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/images/BigBuckBunny.jpg',
    },
    usePoster: true,
  }}
/>
```

**Comment by tolgaduzenli** [comment]
Works for me

**Comment by tanhhkhcndn** [comment]
thanks!
