### ISSUE TITLE
useNetInfo is not exported from '@react-native-community/netinfo'

### ISSUE THREAD

**Issue by adam-acosta** [ihmpavel/expo-video-player#161]
Attempted import error: 'useNetInfo' is not exported from '@react-native-community/netinfo'.

Copy / pasted your example.

Works on iPhone Expo Client. Get above error in browser.

**Comment by ihmpavel** [comment]
Hi,

could you please check, whether you have installed in your `package.json` library `@react-native-community/netinfo` on latest (supported by Expo) version eg. `5.5.1`?

On https://snack.expo.io/ is everything working fine.

**Comment by chichke** [comment]
<img width="927" alt="Capture d’écran 2020-07-31 à 10 50 45 PM" src="https://user-images.githubusercontent.com/26006762/89076288-47142a80-d380-11ea-93e0-454c7a0d1010.png">

Same for me got: 
```javascript
  "@react-native-community/netinfo": "5.5.1",
    "expo-video-player": "^1.5.8",
```

**Comment by leonardopaglia** [comment]
<img width="1285" alt="Screen Shot 2020-10-05 at 19 24 54" src="https://user-images.githubusercontent.com/46678751/95111892-752b3780-0740-11eb-880c-6e8992e01d90.png">

...same also for me.

```
    "@react-native-community/netinfo": "^5.9.7",
    "expo-video-player": "^1.6.0",
```
