### ISSUE TITLE
Using multiple video player instance

### ISSUE THREAD

**Issue by dpatel** [ihmpavel/expo-video-player#18]
I am using multiple video player instances in the list, is there any way to stop the previous video and play the new one on the play button?

**Comment by ihmpavel** [comment]
You can get player status after setting _playbackCallback_ function. (See https://www.npmjs.com/package/expo-video-player#props)

After that on another instance you can set `shouldPlay` property in `videoProps`

**Comment by emmanuel-D** [comment]
I have the same issue, despite the fact that I set the value of `shouldPlay` to **false**
