### ISSUE TITLE
Video controls not fully in viewport

### ISSUE THREAD

**Issue by joshhornby** [ihmpavel/expo-video-player#19]
Hi,

It seems the video player isn't correctly displayed inside the viewport. See below for code and screenshot.

Do you have any advice for positioning the video player so the controls correctly display?

Thanks

```
<View style={{flex: 1, height: '100%', justifyContent: 'center', alignItems: 'center'}}>
                        <VideoPlayer
                            videoProps={{
                                shouldPlay: true,
                                resizeMode: Video.RESIZE_MODE_CONTAIN,
                                source: {
                                    uri: this.state.url,
                                },
                            }}
                            showControlsOnLoad={true}
                            inFullscreen={true}
                            showFullscreenButton={false}
                        />
                    </View>
```

<img width="401" alt="Screenshot 2019-10-16 at 19 48 57" src="https://user-images.githubusercontent.com/5455767/66949223-04ca6880-f04e-11e9-86ba-64b1a29c3286.png">

**Comment by quinnvaughn** [comment]
Have this same issue.

**Comment by Graig123git** [comment]
any luck on this issues guys?

**Comment by dhonata** [comment]
Take off the View

**Comment by florentroques** [comment]
@joshhornby @quinnvaughn @Graig123git @dhonata 
Could any one of you use this [expo code sandbox platform](https://snack.expo.io/) to show your use case?

Thank you

**Comment by mofengfs** [comment]
@florentroques @joshhornby @quinnvaughn @dhonata @ihmpavel 

I can't see the control at all, and the api parameters in the document are as elusive as a fan.

**Comment by mofengfs** [comment]
same

**Comment by mofengfs** [comment]
@joshhornby 
Hey guy. You can do this:
```javascript
<View style={{paddingBottom: 50}}>

   <VideoPlayer />

</View>

```

### Make America Great Again !!!

**Comment by ihmpavel** [comment]
Closing because there is no response in the latest 30 days and hack has been found.
