### ISSUE TITLE
Error: Audio mode attempted to be set without the required keys

### ISSUE THREAD

**Issue by mahyarmoghadam** [ihmpavel/expo-video-player#2]
Error: , setAudioModeAsync error, 1, [Error: Audio mode attempted to be set without the required keys: ["staysActiveInBackground"]]

**Comment by AL1nk2Th3Futur3** [comment]
I don't suppose anybody knows how to fix this? I've come across the same issue

**Comment by mcanzerini** [comment]
+1

**Comment by rafmrss** [comment]
+1

**Comment by chetna-webonise** [comment]
+1

**Comment by Sanjaya94** [comment]
+1

**Comment by ihmpavel** [comment]
Hi, it should be fixed in the next version, which should be ready tomorrow.

**Comment by ihmpavel** [comment]
Fixed in version 1.3.0 #5
