### ISSUE TITLE
FullScreen video on Android

### ISSUE THREAD

**Issue by ShaneKeney** [ihmpavel/expo-video-player#201]
**Describe the bug**
When passing useNativeControls to videoProps on Android the video does not fit properly to device.  The video zooms in a bit cutting off edges.

**To Reproduce**
1.  Pass useNativeControls={true} to videoProps
2.  Click full screen option in bottom right corner

**Expected behavior**
Should perform as iOS does and fit video to screen size of device.  Should not zoom in.  

**Additional infofmation:**
 - Samsung Galaxy s7 (physical device)

**Comment by 9Dave9** [comment]
Same deal for Nexus 6

**Comment by ihmpavel** [comment]
Hi!

Fullscreen example has been added to `example-app`. Please have a look 👀
