### ISSUE TITLE
Fullscreen - On Orientation Change player not updating 

### ISSUE THREAD

**Issue by mobeendev** [ihmpavel/expo-video-player#207]
**On orientation change player not updating its orientation**

I have the following code to set the player to full screen and change its orientation based on device orientation. 
but once the player goes into the landscape mode, it doesn't reset itself on orientation change.

```javascript
<VideoPlayer
          videoProps={{
            shouldPlay: false,
            resizeMode: Video.RESIZE_MODE_CONTAIN,
            source: {
              uri:
                "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
            },
          }}
          isPortrait={true}
          inFullscreen={false}
          switchToLandscape={async () =>
            await ScreenOrientation.lockAsync(
              ScreenOrientation.OrientationLock.LANDSCAPE_LEFT
            )
          }
          showFullscreenButton={true}
          fullscreenExitIcon={<Button>click me </Button>}
          switchToPortrait={async () =>
            await ScreenOrientation.lockAsync(
              ScreenOrientation.OrientationLock.DEFAULT
            )
          }
          showControlsOnLoad={true}
        />
```
Also, I am not able to see the buttons (native & custom button) in the full-screen mode.

**To Reproduce**
1. run the app
2. when the video plays for the first time, click on the default full-screen button
3. It will go into the full-screen mode i.e landscape without considering the device orientation

**Expected behavior**
The video player should come back to the portrait view on device orientation change.
**Additional infofmation:**
 - Type: Real Device 
 - Device:  Huawei
Expo CLI 3.21.13 environment info:
    System:
      OS: macOS 10.15.4
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.18.1 - /usr/local/bin/node
      npm: 6.14.5 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.6 AI-192.7142.36.36.6308749
      Xcode: 11.6/11E708 - /usr/bin/xcodebuild
    npmGlobalPackages:
      expo-cli: 3.21.13

**Comment by shailu26** [comment]
any solution?

**Comment by ihmpavel** [comment]
Hi,

you are using a deprecated prop `isPortrait`. Instead please use `inFullscreen`. (Same behaviour, different name.)

Did you try changing `inFullscreen` prop to reflect orientation changes?

Best regards

**Comment by mobeendev** [comment]
@ihmpavel I have tried, and player shows the video in the full-screen mode, but after that, there's no button to go back.
And It also does not change the orientation to portrait automatically after I go back.

**Comment by mobeendev** [comment]
@ihmpavel I have used [expo-av](https://docs.expo.io/versions/latest/sdk/av/) to resolved my issue.
