### ISSUE TITLE
Masking video image on changing screen

### ISSUE THREAD

**Issue by Narduzzi** [ihmpavel/expo-video-player#235]
Hello,

I would like to keep the video progress from one screen to the other.
Is there a way to show the video on one screen, and when changing screen, keeping the audio but masking the video?
I have already tried to use VideoRef from expo AV but I am struggling in keeping the progress of the video when changing screen.

Thanks in advance!

**Comment by ihmpavel** [comment]
Hi,

what about saving current position of video in the state and on the next screen showing video on given position via `videoProps`, `positionMillis`?

**Comment by Narduzzi** [comment]
Hello @ihmpavel,

I have tried your solution, it works fine in development mode. However, when building the APK, I am running into the following error:
`Player is accessed on the wrong thread`.

Any idea on what I did wrong?
