### ISSUE TITLE
java.lang.IllegalStateException using demo app or by following instructions.

### ISSUE THREAD

**Issue by 9Dave9** [ihmpavel/expo-video-player#244]
**Describe the bug**

Java exception when trying to load video element. 
(I might be missing something in the docs about this not working on emulators/simulators)

Does work on real phones tried this on both iOS and Android. 

Logs:

```

Error: , Encountered a fatal error during playback: java.lang.IllegalStateException, Fatal, Object {}
* [native code]:null in __expoConsoleLog
- node_modules/react-native/Libraries/LogBox/LogBox.js:33:4 in console.error
- node_modules/expo/build/environment/muteWarnings.fx.js:27:4 in error
- node_modules/expo-video-player/dist/index.js:71:19 in defaultProps.errorCallback
- node_modules/expo-video-player/dist/index.js:163:25 in updatePlaybackCallback
- node_modules/expo-av/build/Video.js:58:31 in _handleNewStatus
* http://192.168.1.95:19001/node_modules/expo/AppEntry.bundle?platform=android&dev=true&minify=false&hot=false:204801:32 in _nativeOnError
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:286:4 in invokeGuardedCallbackImpl
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:497:2 in invokeGuardedCallback
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:521:2 in invokeGuardedCallbackAndCatchFirstError
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:683:41 in executeDispatch
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:707:19 in executeDispatchesInOrder
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:872:28 in executeDispatchesAndRelease
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:853:4 in forEachAccumulated
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:897:20 in runEventsInBatch
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:1069:18 in runExtractedPluginEventsInBatch
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:2835:35 in batchedUpdates$argument_0
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:20569:13 in batchedUpdates$1
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:2731:29 in batchedUpdates
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:2834:16 in _receiveRootNodeIDEvent
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:2854:25 in receiveEvent
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:425:19 in __callFunction
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:112:6 in __guard$argument_0
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:373:10 in __guard
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:111:4 in callFunctionReturnFlushedQueue
* [native code]:null in callFunctionReturnFlushedQueue
```
`

**To Reproduce**
1. Clone repo
2. cd to example-app
3. yarn install
4. yarn start
5. Run in simulator

**Expected behavior**
The Video should play without throwing an error.

**Additional infofmation:**
 - Simulated Device - tied on multiple simulated devices all android.
 - Device: [Nxus 6, Pixel 4]
 - OS: [5.1]
 - Expo version (SDK 38)
 - Expo CLI version: 3.23.2

**Additional context**
This breaks on demo exactly the same way.

**Screenshots** (if applicable)

*Proprietary app:*

![Screenshot from 2020-08-17 21-32-51](https://user-images.githubusercontent.com/1446462/90441801-7beae600-e0d1-11ea-8ed9-06055463f69a.png)
![Screenshot from 2020-08-17 21-32-15](https://user-images.githubusercontent.com/1446462/90441797-7b524f80-e0d1-11ea-9426-6f9f912ea5e9.png)

*Example app from this repo(straight yarn install and run):*

![Screenshot from 2020-08-17 21-33-48](https://user-images.githubusercontent.com/1446462/90441848-8dcc8900-e0d1-11ea-9d4b-06f79ac933cf.png)
![Screenshot from 2020-08-17 21-34-15](https://user-images.githubusercontent.com/1446462/90441849-8e651f80-e0d1-11ea-843a-a45c00a03ab8.png)

**Comment by ihmpavel** [comment]
Hi,

have you tried this also on real device or only with virtual ones? (I tried latest version 1.6.0 on actual Android and iPhone and it is working.) Also [snack.expo.io](https://snack.expo.io/) is working, that it is strange behaviour, because it should not, right?

If it is not working on emulators, I'll get in touch with Expo team and mention that in the docs. On the other hand, Expo Snack are emulators...

Thank you 💪

**Comment by 9Dave9** [comment]
Hi, 

Apologies for the late reply. I'm currently getting around this by using real test phones for both platforms. I still get this issue. 

Appreciate you getting back to me.

**Comment by ihmpavel** [comment]
Closing due to no response in the last 30 days.
