### ISSUE TITLE
[BUG - WITH SOLUTION] - videoRef use is ambiguous in examples available and documentation.

### ISSUE THREAD

**Issue by 9Dave9** [ihmpavel/expo-video-player#264]
Currently creating a standard `ref` and passing this to `videoRef` doesn't give me a `current` ref state. i.e `myVideoRef.current == null`

Update the examples with an example of how to use `videoRef` or update the docs. 
Would be happy to do this and submit a PR if I could figure out what really needs to be passed to `videoRef` param as a value.
```

        constructor(props) {                                                                                                                       
            super(props);                                                                                                                           
            this.videoRef = React.createRef();                                                                                                      
            this.state = {                                                                                                                          
            };                                                                                                                                      
          }; 

          <VideoPlayer                                                                                                                      
            videoProps={{                                                                                                                   
              shouldPlay: false,                                                                                                            
              resizeMode: Video.RESIZE_MODE_CONTAIN,                                                                                        
              source: {                                                                                                                     
                uri: this.props.navigation.state.params.videoUrl,                                                                           
              },                                                                                                                            
            }}                                                                                                                              
            videoRef={this.videoRef}                                                                                                 
            isLooping={true}                                                                                                                
            inFullscreen={true}                                                                                                             
            videoBackground='transparent'                                                                                                   
            height={height}                                                                                                                 
            width={width}                                                                                                                   
            showControlsOnLoad={true}                                                                                                       
          />   

```

Result after rendering video:
`this.videoRef == Object { "current": null }`

**Further investigation:**
[In the code](https://github.com/ihmpavel/expo-video-player/blob/master/lib/index.tsx#L117) - type is `Video` for `videoRef`?
Docs seem to expect a `ref` as the type. Not sure I understand how I would pass a `Video` component to `videoRef param` in a `VideoPlayer` component. This is what is making me a little confused. 

Any help would be awesome - thanks.

**Comment by 9Dave9** [comment]
Found some time to get back to this.

The documenation is wrong. `videoRef` is expected as a part of `videoProps` value.

          <VideoPlayer                                                                                                                              
            videoProps={{                                                                                                                                  
              videoRef: this._handleVideoRef,     /* THIS IS CORRECT*/                                                                                                           
              shouldPlay: false,                                                                                                                           
              resizeMode: Video.RESIZE_MODE_CONTAIN,                                                                                                       
              source: {                                                                                                                                    
                uri: this.props.navigation.state.params.videoUrl,                                                                                          
              },                                                                                                                                           
            }}                                                                                                                                             
            isLooping={true}                                                                                                                               
            inFullscreen={true}                                                                                                                            
            videoBackground='transparent'                                                                                                                  
            height={height}                                                                                                                                
            width={width}                                                                                                                                  
            showControlsOnLoad={true}                                                                                                                      
          />

**Comment by ihmpavel** [comment]
Hello, 

if you have time, you could change the docs and the code. I would be happy to merge this PR. Otherwise, I could fix it.

**Comment by johnkmzhou** [comment]
I've noticed that the callback function for videoRef gets called multiple times, almost as if the nested video component is getting rerendered multiple times.

**Comment by 9Dave9** [comment]
@johnkmzhou - could you elaborate please?

How are you seeing this?

**Comment by groteck** [comment]
The issue I think is that is only thinking on the Video example in the expo av documentation that uses a `callback ref`.

https://github.com/ihmpavel/expo-video-player/blob/7484e1ef9f6b9998dcda36a120c76700d13fb5e7/lib/index.tsx#L606-L607

To be able to handle `MutableRefObjects` you will need to identify what is the type of the ref something like:

```typescript
if (typeof videoRef === 'function') ref(component);
if (videoRef && typeof videoRef === 'object') videoRef.current = component; // eslint-disable-line no-param-reassign
// Not much to say react recommended way to update a ref is using it's current ...
``` 
Another option will be just not accept objects and rise an exception like:

```typescript
 React.useEffect(() => {
   if (ref && typeof ref === 'object') { throw new Error('This component only accepts callbacks ref please don't use MutableObjectRef, or an object as a ref');}
 }, [ref]);
```

And the last, not sure if it's possible since I didn't check the code is enforce the videoRef prop to be a function like: `(arg: Video | null) => void`

**Comment by ihmpavel** [comment]
Hi everybody!

Property `ref` has been fixed and example added to `example-app`. Please have a look 👀
