### ISSUE TITLE
Video-player icons are broken on Android when font is set to ''

### ISSUE THREAD

**Issue by bockc** [ihmpavel/expo-video-player#284]
**Describe the bug**
The video-player icons are broken on Android : they display Chinese characters or a cross in a box.

**To Reproduce**
Nothing much, install and try on Android.

**Expected behavior**
Icons should display correctly, just like on iOS

**Additional infofmation:**
 - Type: Real device
 - Device: Samsung Galaxy XCover 4
 - OS: Android 9
 - Package version ^1.6.1
 - I'm not using Expo, it's a bare project

I already tried : updating my dependencies, manually linking react-native-vector-icons, editing android/app/build.gradle, rebooting, cleaning and rebuilding

It works just right on iOS, but I can't get the icons to work properly on Android. I don't really know what to do else and I suspect it's an issue with my project configuration, but I'm unable to pinpoint the culprit.

**Comment by bockc** [comment]
I figured out where the problem came from :
Several years ago we had an issue with Android devices not displaying text due to a specific device font not being properly rendered in react-native. We used a fix to automatically set font to null on all <Text> elements throughout the whole application. Disabling it made the icons appear correctly and hopefully this fix shouldn't be needed anymore.

I don't know if this is intended behaviour to fallback to Chinese icons when there's no font to Text components or if it's a bug. I'm going to leave this issue open in case someone maintaining the project would like to discuss this, but feel free to close it if you consider this not being a bug, though it could be interesting to mention this behaviour in the docs even if this is quite an edge case (maybe in a dedicated section to edge cases ?).

Anyway, here's the code we used to fix our Android font issue in the past :
```
import React from 'react';
import { Platform, Text } from 'react-native';

const oldRender = Text.render;
const styleFix = { ...Platform.select({ android: { fontFamily: '' } }) };
Text.render = (...args) => {
  const origin = oldRender.call(this, ...args);
  return React.cloneElement(origin, {
    style: [origin.props.style, styleFix],
  });
};
```
It's used by simply importing the file containing this code/writing this code in index.android.js and it will automatically set the font for you.

If you need any other details or anything, I'd be glad to provide more informations

**Comment by ihmpavel** [comment]
Hi, this is very weird behavior. Nobody else was faced with the same issue. 

In the latest release, you can change all the icons you want. Example has been added to `example-app`. 

I'm glad you fixed that with this "hack".
