### ISSUE TITLE
Outdated dependency on "expo"

### ISSUE THREAD

**Issue by fubar** [ihmpavel/expo-video-player#3]
Expo's video component has moved to "expo-av" earlier this year: https://github.com/expo/expo/tree/master/packages/expo-av

**Comment by rafaelmoraisdev** [comment]
This would be nice to be fixed, thanks.

**Comment by dean9703111** [comment]
Would this issue Fixed recently?

**Comment by ihmpavel** [comment]
Hi, it should be fixed in the next version, which should be ready tomorrow.

**Comment by ihmpavel** [comment]
Fixed in version 1.3.0 #5
