### ISSUE TITLE
Click the full screen button: `Pass your logic to'switchToLandscape' prop`

### ISSUE THREAD

**Issue by fungmo** [ihmpavel/expo-video-player#322]
## I encountered 3 problems: 
Q1. Triggering the full screen button is invalid and an error is reported; 
Q2. The video is still playing when I go to other pages; 
Q3. When I return to the video page, the video screen displays black.

## Q1.in my genymotion:  `Pass your logic to'switchToLandscape' prop`

![image](https://user-images.githubusercontent.com/16655229/102000863-cbab8800-3d26-11eb-99c9-ddacf1eb8e7a.png)

## Q2. In a video list, I think that when no one wants to click on the next video, the previous video is still playing or when you go to other pages, the video is still playing.

![image](https://user-images.githubusercontent.com/16655229/102000970-96536a00-3d27-11eb-80de-f1a9cb5ae2f2.png)

## Q3. When I return to the video page, the video screen displays black. Don't want this blank board.

![image](https://user-images.githubusercontent.com/16655229/102000912-407ec200-3d27-11eb-84f3-9d4daf48876e.png)

**Comment by csail14** [comment]
I do have the same issues. 
Did you find any help ?

**Comment by mofengfs** [comment]
@csail14 
You can use pictures for lists and modal boxes for videos
