### ISSUE TITLE
How to hide `pauseIcon` by default when opening a video?

### ISSUE THREAD

**Issue by fungmo** [ihmpavel/expo-video-player#331]
I don't want users to be bothered by `pauseIcon` as soon as they open the video. Because it affects the visual experience. I want it to be hidden.
In other words, I don't know how to use parameters whose type is `JSX.Element`. I can't see a basic example.

**Comment by ihmpavel** [comment]
Hi!

Property have a look in the `example-app`, where is example of what you are trying to do.
