### ISSUE TITLE
⚠️ New features, fixes and upcoming development

### ISSUE THREAD

**Issue by ihmpavel** [ihmpavel/expo-video-player#352]
Hi everyone!

It has been long time since I created this library. Unfortunately, last months I have not got time to dedicate time. A lot of more issues, questions and ideas were coming. 

Because every week this library gets more and more downloads, I decided to put more effort and make it even better. In the next weeks - after school exams - I will be focusing more.

I want to rewrite, simplify and fix known bugs. Also I want to close a lot of issues, which includes

- Adding license https://github.com/ihmpavel/expo-video-player/issues/334 (I need to check this before. Any ideas which one to choose?)
- Fixing state update https://github.com/ihmpavel/expo-video-player/issues/326
- Add features https://github.com/ihmpavel/expo-video-player/issues/331
- Check icon rendering and fixing it https://github.com/ihmpavel/expo-video-player/issues/284
- Fixing reference https://github.com/ihmpavel/expo-video-player/issues/264
- Adding more features https://github.com/ihmpavel/expo-video-player/issues/261
- Adding FAQ section about using YouTube and more
- Updating demo app, packages and checking compatibility and many more

Looking forward to next version! PR's are welcome!

Thank you for using this library and almost reaching 100 ⭐.

**Comment by dlenskyi** [comment]
@ihmpavel Hi there!
First of all, thank you for this awesome wrapper for expo-av package!
Can you tell me, any updates regarding issues you described above?

**Comment by ihmpavel** [comment]
It has been long time since I posted an update. I am currently rewriting entire library to match high standards. I have last week of my university exams for this semester and with work it is a bit harder than I though. 

I'll be dedicating next weekend entirely on this library with some testing and going through all issues. Also I am planning to describe better how to achieve `Fullscreen` mode, because a lot of questions are about this.

Right now it is looking good, but wait till end.

Looking forward 🥳 

Also I would like to thank everyone for 100 ⭐

**Comment by ihmpavel** [comment]
Version [2.0.0](https://github.com/ihmpavel/expo-video-player/releases/tag/v2.0.0) has been released with rewritten code, simplified logic and with a lot of more styling options.

**Comment by emadbaqeri** [comment]
Hi @ihmpavel, in issue #363 you mentioned this error (The AVPlayerItem instance has failed with the error code -1002 and domain "NSURLErrorDomain".) is going to be resolved but I'm facing the same error still

**Comment by VedP20** [comment]
Hi @ihmpavel, I'd like to request the addition of an audio control icon for muting when needed, as well as some customization options to better align the controls with user preferences. It would be great to explore theming options for a more personalized touch. Could you please incorporate these enhancements?
