### ISSUE TITLE
iOS: fatal error during playback: The AVPlayerItem instance has failed with the error code -1008 and domain "NSURLErrorDomain".

### ISSUE THREAD

**Issue by KaranChimple** [ihmpavel/expo-video-player#363]
I'm facing this issue on iOS even on the latest version of expo-video-player. I have the video player running on the parent screen which lists a group of posts and when I click on that particular post with the video, the video from the parent screen continues to run and in the child screen, I get this error, "Encountered a fatal error during playback: The AVPlayerItem instance has failed with the error code -1008 and domain "NSURLErrorDomain".

_Originally posted by @KaranChimple in https://github.com/ihmpavel/expo-video-player/issues/71#issuecomment-783582417_

**Comment by ihmpavel** [comment]
Hi, this should be fixed in the next release https://github.com/ihmpavel/expo-video-player/issues/352

**Comment by jatinhemnani01** [comment]
@ihmpavel I'm facing the same problem, how did you fix it?

**Comment by arapocket** [comment]
I am experiencing this as well

**Comment by hayata-suenaga** [comment]
I'm also experiencing the same error with `"expo-av": "~14.0.5",`
