### ISSUE TITLE
inFullscreen={true} triggers the switchToLandscape callback

### ISSUE THREAD

**Issue by mischkew** [ihmpavel/expo-video-player#41]
**Observed Behaviour**

When launching the example app from the README, the bottom-right icon for launching into fullscreen mode is visible. When clicking that button a suggestion is given to use ScreenOrientation to switch the screen into Landscape orientation.

**Expected Behaviour**

As I set the video with `inFullscreen={true}` I would have expected to see the exit fullscreen button. When clicking it I would have expected to see the suggestion to use ScreenOrientation to switch the screen into Portrait orientation.

I do get the expected behaviour when setting the `inFullscreen` prop to false. From my current understanding the boolean logic should be switched to solve this issue.

Do I have a misunderstanding? Thanks for the support! :)

**Comment by ihmpavel** [comment]
Hi, thanks for reporting this issue.

I have just checked the behavior and you are right. The logic and icons are inverted.

I'll fix this during this week (before the fix, you can revert logic in prop `inFullscreen` and everything shold be working fine.)

**Comment by ihmpavel** [comment]
Fixed in #46

**Comment by dzilva** [comment]
> Fixed in #46
> 
> Version 1.5.6

Hello,
I can't see the expand icon when goes to full screen. In portrait mode it's fine and show the expand icon and when I click it goes to Landscape mode. In landscape mode there is not showing any controller.

**Comment by ihmpavel** [comment]
Hi, can you please create minimal reproduction?

Like this one: https://snack.expo.io/ByolZzCGI (https://github.com/ihmpavel/expo-video-player/issues/57#issuecomment-583905424)
