### ISSUE TITLE
FullScreen not working Help

### ISSUE THREAD

**Issue by thareekanvar** [ihmpavel/expo-video-player#412]
When i click the fullscreen button .its not working 

my code :

```
<VideoPlayer
            videoProps={{
              shouldPlay: false,
              resizeMode: Video.RESIZE_MODE_CONTAIN,
              source: {
                uri: url,
              },
            }}
            inFullscreen={false}
            showControlsOnLoad={true}
            showFullscreenButton={true}
            width={300}
            height={200}
          />
```

**Comment by ihmpavel** [comment]
Hello, that looks like you do not have custom function `switchToPortrait` and `switchToLandscape`.

Something like 
```
<VideoPlayer
  switchToLandscape={async () =>
    await ScreenOrientation.lockAsync(
      ScreenOrientation.OrientationLock.LANDSCAPE_LEFT
    )
  }
  switchToPortrait={async () =>
    await ScreenOrientation.lockAsync(
      ScreenOrientation.OrientationLock.DEFAULT
    )
  }
  ...
/>
```

**Comment by thareekanvar** [comment]
> Hello, that looks like you do not have custom function `switchToPortrait` and `switchToLandscape`.
> 
> Something like
> 
> ```
> <VideoPlayer
>   switchToLandscape={async () =>
>     await ScreenOrientation.lockAsync(
>       ScreenOrientation.OrientationLock.LANDSCAPE_LEFT
>     )
>   }
>   switchToPortrait={async () =>
>     await ScreenOrientation.lockAsync(
>       ScreenOrientation.OrientationLock.DEFAULT
>     )
>   }
>   ...
> />
> ```

Thanks for your reply i used this ,but the video not in fullscreen its will changing the screenOrientation . please help

**Comment by ihmpavel** [comment]
Hi, you need to change also `width` and `height` props. 

```
<VideoPlayer
  ...
  height={Dimensions.get('window').height}
  width={Dimensions.get('window').width}
/>
```

**Comment by ihmpavel** [comment]
Hi everybody!

Fullscreen example has been added to `example-app`. Please have a look 👀
