### ISSUE TITLE
How to achieve preloading?

### ISSUE THREAD

**Issue by fungmo** [ihmpavel/expo-video-player#413]
**Describe the bug**
I tried to test and play the local video on the emulator and the real machine, but the results were disappointing. It was always slow and the playback was not smooth.

**Expected behavior**
Hope it can be pre-loaded like a youtube player, and the video playback is smooth.
![image](https://user-images.githubusercontent.com/16655229/119030791-ede3b900-b9dc-11eb-8696-09003dfe8a85.png)

**Additional infofmation:**
 - Type: [Simulator/Real device]
 - Device: [android]
 - OS: [android 9.0]
 - Package version ["^1.6.1"]
 - Expo version (40.0.0)
 - Expo CLI version 4.4.1

**Comment by ihmpavel** [comment]
Hi, unfortunately this is the limitation of [Expo](https://docs.expo.io/versions/latest/sdk/video)
