### ISSUE TITLE
How to set the size of the slider?

### ISSUE THREAD

**Issue by fungmo** [ihmpavel/expo-video-player#424]
The progress bar slider has only color settings and no size settings. And there is no separate setting from icons such as play.

![image](https://user-images.githubusercontent.com/16655229/120585295-100d1a80-c464-11eb-8d1e-8c89a26f2105.png)

**Comment by ihmpavel** [comment]
Hi,
what device are you using? Also I would like to mention, that in the next major version, you will be able to set all the Slider properties. 
Check https://github.com/ihmpavel/expo-video-player/issues/352 for more information
