### ISSUE TITLE
Using localUri prop on source doesn't load media

### ISSUE THREAD

**Issue by Bigrev** [ihmpavel/expo-video-player#432]
**Describe the bug**
Hi! Using "localUri" prop to pass a media uri inside the device doesn't play the video (it keeps loading), but defining it inside "uri" instead plays just fine.

**Additional information:**
 - Type: iOS Simulator
 - Device: iPhone 12
 - OS: 14.5
 - Expo CLI version 4.4.3

**Comment by ihmpavel** [comment]
Hi!

I have checked this and in the latest release it is working fine. In the `example-app` is relevant code. Please have a look 👀
