### ISSUE TITLE
TouchableNativeFeedback.Ripple is not a function

### ISSUE THREAD

**Issue by chris-aeviator** [ihmpavel/expo-video-player#433]
**Describe the bug**
When upgrading expo from SDK V.39 to SDK V.41 I'm following the upgrade V1->V2 instructions for expo-video-player. However after migration, a previously working video player throws `TouchableNativeFeedback.Ripple is not a function` on expo-web.

**To Reproduce**
1.  Load VideoPlayer with expo-sdk v.41 in expo web

**Expected behavior**
The video player should still load after the upgrade

**Additional infofmation:**
 - Type: Expo web
 - Device: Desktop
 - OS: Arch Linux / Firefox  V88
 - Package Version: 2.0.0
 - Expo version: 41.0.0
 - Expo CLI version: : 4.5.2

**Comment by chris-aeviator** [comment]
I propose that `<TouchableNativeFeedback onPress={togglePlay} background={TouchableNativeFeedback.Ripple('white', true)}>` becomes 

```
              <TouchableNativeFeedback onPress={togglePlay} background={TouchableNativeFeedback?.Ripple('white', true) ?? null}>
```

**Comment by ihmpavel** [comment]
Hi, 
while releasing v2 i did not check properly the web version. 

During this week I'll try to focus and fix all possibly errors. 

Maybe as temporary fix not to throw an error in the application I should release patch fix today.

**Comment by chris-aeviator** [comment]
Nice to hear that, and glad you want to keep support up for the web version.

https://stackoverflow.com/questions/43244306/react-native-touchablenativefeedback-ripple-is-not-function

suggests to use  TouchableHighlight or TouchableOpacity

**Comment by ihmpavel** [comment]
Hi, 
I have changed the code to reflect user platform. On Android, buttons are `<TouchableNativeFeedback />` and on other platforms I changed the buttons to `<TouchableOpacity />`. I am not sure about the visual experience using `<TouchableOpacity />`. What do you think? Is it ok or should I use other `Touchable` element?

I created [PR](https://github.com/ihmpavel/expo-video-player/pull/434/files) with the changes.

Let me know, what do you think. I am ready to create patch release immediately.

**Comment by chris-aeviator** [comment]
@ihmpavel I will check this tomorrow - for my current release I completely removed the Ripple but I'm happy to try this in the morning tomorrow! Thx!

**Comment by ihmpavel** [comment]
Merged into master. Version `2.0.1` https://github.com/ihmpavel/expo-video-player/pull/434
