### ISSUE TITLE
Video Player initial icon is a Pause instead of a Play

### ISSUE THREAD

**Issue by hanijazzar** [ihmpavel/expo-video-player#438]
When the player is first loaded, the icon shows a Pause icon. After I click the pause icon, it turns into Play icon but the video still paused. Then after I click the Play button it starts playing. Basically i need to click twice to play a video. On both Android and iOS and using default config with {shouldPlay: false,  isPlaying: false,   isLooping: false,} The screenshot below shows directly when i display the video player
![Screenshot_20210626-150752_Expo Go](https://user-images.githubusercontent.com/12611798/123511099-7b779000-d690-11eb-896a-ca04d72f4f19.jpg)

**Comment by ihmpavel** [comment]
Hi, that is weird behavior. Did you experienced same issue in the [example-app](https://github.com/ihmpavel/expo-video-player/tree/master/example-app)?

Also could you please try this as example? 

This is working fine for me
```
<VideoPlayer
  videoProps={{
    shouldPlay: false,
    resizeMode: Video.RESIZE_MODE_CONTAIN,
    source: {
      uri: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    },
  }}
/>
```

**Comment by hanijazzar** [comment]
The example works well. Seems it's an edge case as I'm trying to load multiple videos in a carousel.

**Comment by niallfarrell91** [comment]
I've noticed this too. It doesnt happen in the sample app.
It seems to relate to `playbackCallback` . It happens for me when I set state inside the playbackCallback
```
              playbackCallback={(status: AVPlaybackStatus) => {
                if (status.isLoaded) {
                  setPlaybackStatus(status)
                }
              }}
```

**Comment by rafaelgilead** [comment]
any solution for this problem?

**Comment by allencit** [comment]
I'm facing the same issue, it seems that this issue will occur when it is rendered to hidden elements.

**Comment by adamtsai1** [comment]
I'm experiencing the same issue. Seems to be happening when I dynamically resize the video. I was able to get around it by manually pausing the player after resize:

`videoRef.current.pauseAsync()`
