### ISSUE TITLE
How can I alert something when the video just finish?

### ISSUE THREAD

**Issue by mizukageyama** [ihmpavel/expo-video-player#439]
Can someone help me in my problem? I am struggling, and new at react native

https://stackoverflow.com/questions/68147377/how-to-alert-something-when-the-video-ends-on-expo-video-player-on-react-native

**Comment by ihmpavel** [comment]
Hi,

you can use `playbackCallback`. More info in the official [Expo documentation](https://docs.expo.io/versions/latest/sdk/video/).

```
<VideoPlayer
  playbackCallback={(e) => {
    if (e.isLoaded) {
      // Video replay ended
      console.log(e.didJustFinish)
    }
  }}
  videoProps={{
    shouldPlay: true,
    resizeMode: Video.RESIZE_MODE_CONTAIN,
    source: {
      uri: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    },
  }}
/>
```

**Comment by mizukageyama** [comment]
Thank you so much!
