### ISSUE TITLE
Replay icon display on iOS

### ISSUE THREAD

**Issue by andreinegrea14** [ihmpavel/expo-video-player#469]
I can't get over a bug that occurs on iOS only, the replay icon do not appear immediately after the video finished. The behavior is this: the video ends, play icon appears, if play icon is pressed the icon switches to replay.

**Expected behavior**
The expected behavior is that the replay icon appears after the video ends, not the play icon. Did not had this issue on android.

**Additional information:**
 - Type: Both Simulator & iPhone device
 - Device: Any
 - OS: iOS 14.0+
 - Package version 2.0.1
  - Expo version 39

Is this a singular issue ? I didn't find any related issues here.

**Comment by MadhavNasit** [comment]
> I can't get over a bug that occurs on iOS only, the replay icon do not appear immediately after the video finished. The behavior is this: the video ends, play icon appears, if play icon is pressed the icon switches to replay.
> 
> **Expected behavior** The expected behavior is that the replay icon appears after the video ends, not the play icon. Did not had this issue on android.
> 
> **Additional information:**
> 
> * Type: Both Simulator & iPhone device
> * Device: Any
> * OS: iOS 14.0+
> * Package version 2.0.1
> * Expo version 39
> 
> Is this a singular issue ? I didn't find any related issues here.

+1

**Comment by MadhavNasit** [comment]
> That is weird. Unfortunately I am not able to reproduce, but I will be happy to merge a fix :/

@ihmpavel, replace below lines in index.js in dist on line no. 113 of updatePlaybackCallback function,
`setPlaybackInstanceInfo(Object.assign(Object.assign({}, playbackInstanceInfo), { position: status.positionMillis, duration: status.durationMillis || 0, state: status.didJustFinish`
with
`position: status.positionMillis, duration: status.durationMillis || 0, state: status.positionMillis == status.durationMillis`

**Comment by ihmpavel** [comment]
Hi, this will solve this issue? 
If so I'll be happy to accept PR/create PR from this

**Comment by OneHatRepo** [comment]
Solved it for me! Can you please merge it in?

**Comment by ihmpavel** [comment]
Get ready for new version `2.0.4`
