### ISSUE TITLE
@react-native-community/slider Isn't support on Expo

### ISSUE THREAD

**Issue by herotatin** [ihmpavel/expo-video-player#47]
Hi,  I got error : Invariant Violation: requireNativeComponent: "RNCSlider" was not found in the UIManager, using version 1.5.6.  Looks like @react-native-community/slider doesn't work with Expo projects.

Please see:
https://github.com/expo/expo/issues/4300

**Comment by at74S6v** [comment]
Having the same issue. Tried running 
> 1- `npm install @react-native-community/slider –save`
> 2- `react-native link @react-native-community/slider`
> 3- include in your script file like `import { Slider } from 'react-native'` instead of `import Slider from '@react-native-community/slider';`
> 
> then `expo start --clear`
as described [here](https://github.com/react-native-community/react-native-slider/issues/41#issuecomment-561912319) -- didn't work. I'm using the latest version, expo-cli@3.11.7.

**Comment by bapjiws** [comment]
Having the same issue. Tried running 

> 1- `npm install @react-native-community/slider –save`
> 2- `react-native link @react-native-community/slider`
> 3- include in your script file like `import { Slider } from 'react-native'` instead of `import Slider from '@react-native-community/slider';`
> 
> then `expo start --clear`

as described [here](https://github.com/react-native-community/react-native-slider/issues/41#issuecomment-561912319) -- didn't work. I'm using the latest version, expo-cli@3.11.7.

**Comment by ihmpavel** [comment]
During today I will look into this and maybe revert the library. 

Please, use version 1.5.5 until this is fixed. (Sorry for the troubles...)

**Comment by ihmpavel** [comment]
Should be fixed #48 

Closing this thread. If you encounter same error, I can reopen this.
