### ISSUE TITLE
mute icon/functionality support

### ISSUE THREAD

**Issue by ehsan6sha** [ihmpavel/expo-video-player#474]
**Is your feature request related to a problem? Please describe.**
Right now there is no icon or support for mute/unmute functionality.

**Describe the solution you'd like**
I have implemented a mute icon support in this branch for my usecase. Let me know if you like to a pull request to merge it:
https://github.com/functionland/expo-video-player

**Comment by ihmpavel** [comment]
Functionality added in version `2.1.0` 🎉
