### ISSUE TITLE
Unable to resolve "@react-native-community/netinfo" from "node_modules/expo-video-player/dist/index.js"

### ISSUE THREAD

**Issue by Dolidodzik** [ihmpavel/expo-video-player#55]
`Unable to resolve "@react-native-community/netinfo" from "node_modules/expo-video-player/dist/index.js"` - shows up after running `expo install expo-video-player`.

EDIT: I fixed that issue by running `expo install @react-native-community/netinfo`

**Comment by adeeltahir200** [comment]
I have the same issue
Unable to resolve "@react-native-community/netinfo" from "node_modules\expo-video-player\dist\index.js"

**Comment by ihmpavel** [comment]
Hi, that looks like you do not have installed `@react-native-community/netinfo` in your _package.json_. (You can check before next steps.)

Try installing `@react-native-community/netinfo` via _expo-cli_ `expo install @react-native-community/netinfo`, _yarn_ `yarn add @react-native-community/netinfo` or _npm_ `npm i @react-native-community/netinfo`
