### ISSUE TITLE
how to handle events when video is no longer in view

### ISSUE THREAD

**Issue by Graig123git** [ihmpavel/expo-video-player#57]
I have this component in a flat list, my question is how can i stop the video from playing once 
the flatlist item is no longer in view i.e for example i scrolled to another item.

**Comment by ihmpavel** [comment]
You can pause/stop video by it's reference

```
<VideoPlayer      
  ...
  videoProps={{
    ref: v => (video = v)
 }}
/>
```

And in code:
_Pause_
- `await video.playbackObject.pauseAsync()` _or_
- `playbackObject.setStatusAsync({ shouldPlay: false })`
_Stop_
- `playbackObject.stopAsync()` _or_
- `playbackObject.setStatusAsync({ shouldPlay: false, positionMillis: 0 })`

(You have to call to stop/pause when the item is not in view)

You can read more in [Expo docs](https://docs.expo.io/versions/latest/sdk/av/#playback-api).

**Comment by Graig123git** [comment]
Thank you!!

**Comment by Graig123git** [comment]
is there any working code show this  in a class base or functional
component?
my code below cant access the ref
am getting the error at this line await this.v.playbackObject.pauseAsync();
which states that ref is undefined and it cannot be evaluated.


import * as WebBrowser from 'expo-web-browser';
import React, { useRef } from 'react';
import { Image, Dimensions, Platform, ScrollView, StyleSheet, Text,
TouchableOpacity, View } from 'react-native';
import Constants from 'expo-constants';
import * as Sharing from 'expo-sharing';
import * as FileSystem from 'expo-file-system';
import { Video } from 'expo-av';
import VideoPlayer from 'expo-video-player';
const image_source =
'
https://images.unsplash.com/photo-1508138221679-760a23a2285b?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&w=1000&q=80
';

class Card extends React.Component {
constructor(props) {
super(props);
this.v = React.createRef();
}
share() {
FileSystem.downloadAsync(image_source, FileSystem.documentDirectory +
'.jpeg')
.then(({ uri }) => {
console.log('Finished downloading to ', uri);

Sharing.shareAsync(uri);
})
.catch(error => {
console.error(error);
});
}
_handleVideoRef = async () => {
await this.v.playbackObject.pauseAsync();
};

render() {
const { ...props } = this.props;
return (
<View style={styles.cardRetangle}>
{props.vid ? (
<VideoPlayer
height={150}
width={Dimensions.get('window').width * 0.95}
showControlsOnLoad={true}
videoProps={{
ref: v => (video = v),
shouldPlay: props.vedioPlay,
resizeMode: Video.RESIZE_MODE_STRETCH,
source: {
uri: '
http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4
'
}
}}
inFullscreen={true}
/>
) : null}
{props.img ? <Image resizeMode='stretch' style={styles.image} source={{ uri:
props.img }} /> : null}
<Text style={styles.textContainer}>{props.des}</Text>
<View style={props.like && props.share ? styles.interactiveButtons : styles.
recycleBin}>
{props.like ? (
<TouchableOpacity onPress={() => share()}>
<Image source={props.like} />
</TouchableOpacity>
) : null}
{props.share ? (
<TouchableOpacity onPress={() => this._handleVideoRef()}>
<Image source={props.share} />
</TouchableOpacity>
) : null}
{props.delete ? (
<TouchableOpacity style={styles.recycleBin} onPress={() => share()}>
<Image source={props.delete} />
</TouchableOpacity>
) : null}
</View>
</View>
);
}
}

const styles = StyleSheet.create({
cardRetangle: {
width: '95%',
borderRadius: 10,
backgroundColor: '#ffffff',
alignSelf: 'center',
shadowColor: '#000',
shadowOffset: {
width: 0,
height: 12
},
shadowOpacity: 0.58,
shadowRadius: 16.0,

elevation: 24
},

image: {
width: '100%',
height: 150
},

textContainer: {
flex: 1,
fontSize: 12,
lineHeight: 21,
letterSpacing: 0,
textAlign: 'left',
padding: 15
},
interactiveButtons: {
flexDirection: 'row',
padding: 20,
justifyContent: 'space-between'
},
recycleBin: {
flexDirection: 'row',
padding: 20,
justifyContent: 'flex-end'
}
});

export default Card;

**Comment by ihmpavel** [comment]
Minimal reproduction: https://snack.expo.io/ByolZzCGI
