### ISSUE TITLE
Can width and height props be in percentage ?

### ISSUE THREAD

**Issue by Graig123git** [ihmpavel/expo-video-player#58]
Can we have the width and height props of the video component be in percentage instead of numbers ?

**Comment by ihmpavel** [comment]
Right now it is not implemented to accept strings (percentage...), due to some logic with screen ratios.

You can pass number as _percentage value_ this way (I do not recommend, but it is possible).

```
<VideoPlayer
  ...
  width={Dimensions.get('window').width * .5} // 50 % of width
  height={Dimensions.get('window').height * .3} // 30 % of height
/>
```

**Comment by Graig123git** [comment]
Thank you!!!
