### ISSUE TITLE
expo-video-player not working for expo version 36

### ISSUE THREAD

**Issue by devramjava** [ihmpavel/expo-video-player#65]
App crashing when using expo-video-player

**Comment by ihmpavel** [comment]
Hi, what version of this package are you using (also @react-native-community/netinfo and expo-av version). (Do you see some errors?)

Can you create some minimal reproduction? (snack.expo.io)

I am unable to simulate this (SDK 36 with latest version is working for me).

**Comment by devramjava** [comment]
i'm using "expo-av": "^8.0.0"

**Comment by ihmpavel** [comment]
The issue will be closed soon, due to lack of information.

**Comment by ihmpavel** [comment]
Closing, can be reopened again.
