### ISSUE TITLE
Video Player Not Working After Build on Android

### ISSUE THREAD

**Issue by dzilva** [ihmpavel/expo-video-player#69]
In android (after the build and got the apk file) I installed the APK file on emulator/real device. This is what happened when I open the app.

Without building APK file it working fine on emulator and real device. But when I got the APK file and after install it this error happened.

I mentioned below my code. Please help me to solve this.

THIS ISSUE ONLY HAPPEN WHEN **BUILD THE APK FILE** FOR **ANDROID** AND **ONLY IN LANDSCAPE MODE**!

![Screenshot_1582182884](https://user-images.githubusercontent.com/30325568/74909723-ea7b0f80-53de-11ea-8d7c-f47be64f2b1d.png)

**Comment by ihmpavel** [comment]
The issue you are experiencing is that the video is not aligned on the top (left) corner?

If yes, try using `StyleSheet.absoluteFill` (or some similar styles) - [StyleSheet Documentation](https://facebook.github.io/react-native/docs/stylesheet#absolutefill)

**Comment by dzilva** [comment]
This is my style sheet here,

const styles = StyleSheet.create({
  container: {
    alignSelf: 'center',
    justifyContent: 'center',
    backgroundColor: '#FFF',
    flex: 1,
  },
  video: {
    flex: 1,
    justifyContent: 'center',
  }
});

**Comment by dzilva** [comment]
And this is what inside my return function,

<View style={styles.container}>
     <View style={styles.video}>
          <VideoPlayer
            videoProps={{
              shouldPlay: false,
              resizeMode: Video.RESIZE_MODE_CONTAIN,
              source: {
                uri: url,
              },
            }}
            inFullscreen={true}
            showControlsOnLoad={true}
            showFullscreenButton={true}
            width={this.state.width}
            height={this.state.height}
          />
   </View>
</View>

**Comment by ihmpavel** [comment]
In my app I am currently using (with success) this approach. (Working also on Android - real device)

_Code_
```
return (
  <View style={styles.container}>
    <VideoPlayer
      height={Dimensions.get('window').height}
      width={Dimensions.get('window').width}
      ...
  </View>
)
```

_Styles_
```
const styles = StyleSheet.create({
  container: {
    alignItems: 'center',
    backgroundColor: 'black',
    flex: 1,
    justifyContent: 'center',
    ...StyleSheet.absoluteFillObject,
  },
})
```

**Comment by dzilva** [comment]
> In my app I am currently using (with success) this approach. (Working also on Android - real device)
> 
> _Code_
> 
> ```
> return (
>   <View style={styles.container}>
>     <VideoPlayer
>       height={Dimensions.get('window').height}
>       width={Dimensions.get('window').width}
>       ...
>   </View>
> )
> ```
> 
> _Styles_
> 
> ```
> const styles = StyleSheet.create({
>   container: {
>     alignItems: 'center',
>     backgroundColor: 'black',
>     flex: 1,
>     justifyContent: 'center',
>     ...StyleSheet.absoluteFillObject,
>   },
> })
> ```

Also working with android build APK file installation?

**Comment by ihmpavel** [comment]
Yes

(I have forgotten one `View`, but it should not make a difference).

Styles are the same, but the render function looks like this.

```
// because before buffering nothing shows
const viewStyle = isLoaded ? StyleSheet.absoluteFillObject : { width: 0, height: 0, opacity: 0 }

return (
  <View style={styles.container}>
    <StatusBar hidden={true} />

    {!isLoaded && <ActivityIndicator style={StyleSheet.absoluteFillObject} size='large' />}

    <View style={viewStyle}>
      <VideoPlayer
        height={Dimensions.get('window').height}
        width={Dimensions.get('window').width}
        ...
      />
    </View>
  </View>
)
```

Please let me know, if it is working for you. 😀

**Comment by dzilva** [comment]
> Yes
> 
> (I have forgotten one `View`, but it should not make a difference).
> 
> Styles are the same, but the render function looks like this.
> 
> ```
> // because before buffering nothing shows
> const viewStyle = isLoaded ? StyleSheet.absoluteFillObject : { width: 0, height: 0, opacity: 0 }
> 
> return (
>   <View style={styles.container}>
>     <StatusBar hidden={true} />
> 
>     {!isLoaded && <ActivityIndicator style={StyleSheet.absoluteFillObject} size='large' />}
> 
>     <View style={viewStyle}>
>       <VideoPlayer
>         height={Dimensions.get('window').height}
>         width={Dimensions.get('window').width}
>         ...
>       />
>     </View>
>   </View>
> )
> ```
> 
> Please let me know, if it is working for you. 😀

Let me try this 😀

**Comment by dzilva** [comment]
Still I'm facing same issue 🤔

![image](https://user-images.githubusercontent.com/30325568/74913706-3336c680-53e7-11ea-878c-fb671c14595e.png)

**Comment by dzilva** [comment]
In portrait mode no issue.

![image](https://user-images.githubusercontent.com/30325568/74913799-5f524780-53e7-11ea-90d9-ed99bdd9f147.png)

Issue only happens when the landscape mode on android.

![image](https://user-images.githubusercontent.com/30325568/74913946-9de80200-53e7-11ea-8a68-0e018169e89e.png)

**Comment by dzilva** [comment]
Here is my full code in App.js

import { ScrollView, StyleSheet, View, Dimensions } from 'react-native'
import { Video } from 'expo-av'
import React from 'react'
import VideoPlayer from 'expo-video-player'
import { ScreenOrientation } from 'expo'

const { width, height } = Dimensions.get('window');

export default class App extends React.Component {

  static navigationOptions = ({ navigation }) => ({
    header: null,
    tabBarVisible: false,
  });

  constructor(props) {
    super(props);
    this.state ={
      isPortrait: true,
      width: width,
      height: height
    }
  }

  componentDidMount() {
    console.log('componentDidMount')
    ScreenOrientation.lockAsync(ScreenOrientation.OrientationLock.ALL)
    Dimensions.addEventListener('change', this._orientationChangeHandler.bind(this));
  }

  componentWillUnmount() {
    console.log('componentWillUnmount')
    ScreenOrientation.lockAsync(ScreenOrientation.OrientationLock.PORTRAIT);
    Dimensions.removeEventListener('change', this._orientationChangeHandler);
  }

  _orientationChangeHandler = (dims) => {
    console.log('_orientationChangeHandler')
    const { width, height } = dims.window;
    const isLandscape = width > height;
    this.setState({ isPortrait: !isLandscape });
    ScreenOrientation.lockAsync(ScreenOrientation.OrientationLock.ALL)
    this.setState({ width: width })
    this.setState({ height: height })
  }

  switchToLandscape = () => {
    console.log('switchToLandscape')
    ScreenOrientation.lockAsync(ScreenOrientation.OrientationLock.LANDSCAPE)
  }

  switchToPortrait = () => {
    console.log('switchToPortrait')
    ScreenOrientation.lockAsync(ScreenOrientation.OrientationLock.PORTRAIT)
  }

  render() {
    return (
      <View style={styles.container}>
        <View style={styles.video}>
          <VideoPlayer
            videoProps={{
              shouldPlay: false,
              resizeMode: Video.RESIZE_MODE_CONTAIN,
              source: {
                uri: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
              },
            }}
            inFullscreen={true}
            showControlsOnLoad={true}
            showFullscreenButton={false}
            height={Dimensions.get('window').height}
            width={Dimensions.get('window').width}
          />
        </View>
      </View>
    )
  }
}

const styles = StyleSheet.create({
  container: {
    alignItems: 'center',
    backgroundColor: 'black',
    flex: 1,
    justifyContent: 'center',
    ...StyleSheet.absoluteFillObject,
  },
  video: {
    flex: 1,
    justifyContent: 'center',
  }
});

**Comment by ihmpavel** [comment]
Finally 🙌

Build an app with you configuration. 

There are 2 possibilities

1) Replace your `video` styles with `StyleSheet.absoluteFillObject` (instead of `flex: 1, justifyContent: 'center'`)

_or_

2) The problem is caused by `justifyContent: 'center'` (idk why) - remove it. Everything should be working

Eg:
```
...
video: {
  flex: 1,
}
...
```

**Comment by dzilva** [comment]
> Finally 🙌
> 
> Build an app with you configuration.
> 
> There are 2 possibilities
> 
> 1. Replace your `video` styles with `StyleSheet.absoluteFillObject` (instead of `flex: 1, justifyContent: 'center'`)
> 
> _or_
> 
> 1. The problem is caused by `justifyContent: 'center'` (idk why) - remove it. Everything should be working
> 
> Eg:
> 
> ```
> ...
> video: {
>   flex: 1,
> }
> ...
> ```

Yeah it's work!!! ❤️❤️ You save me life ❤️❤️
Actually it's a my fault 😆
Thanks you so much and I wish to make more projects like this! It's a awesome player!

**Comment by dzilva** [comment]
Thanks you so much @ihmpavel ❤️❤️❤️❤️

**Comment by dzilva** [comment]
One more thing if you can help me!

I'm actually using Expo. when I run the code in iPhone real device (using expo) it will crash the app and close. (When the Video Screen loading)

**Comment by dzilva** [comment]
> One more thing if you can help me!
> 
> I'm actually using Expo. when I run the code in iPhone real device (using expo) it will crash the app and close. (When the Video Screen loading)

Solved! It's a @react-native-community/netinfo issue and because I'm using expo so I downgrade it to version 4.6.0. problem solved!
