### ISSUE TITLE
Component Dimensions 

### ISSUE THREAD

**Issue by VaMusaka** [ihmpavel/expo-video-player#7]
if there a way of setting my own custom dimensions to the VideoPlayer Component? 
it looks like it is reading the width and height of the device and forcing the component to be in full screen with a black backdrop. I would like the video to only occupy a specified section of the screen and not have it in full screen. 
Also, when l have the bottomNavigation on the same page the controls are hidden.

**Comment by ihmpavel** [comment]
Hi, you can set dimensions using props `width` and/or `height`. 

Check the latest version `1.4.0` and PR #9
