### ISSUE TITLE
Android: Play button not centered and play controls cut off with Carousel

### ISSUE THREAD

**Issue by kevgrig** [ihmpavel/expo-video-player#70]
**Describe the bug**
Android: Play button not centered and play controls cut off with Carousel.

**To Reproduce**
1. https://snack.expo.io/@git/github.com/kevgrig/testvideo
2. Open on Android
3. Observe play button is not centered
4. Observe end duration and fullscreen components are not visible.

**Expected behavior**
Video content is constrained to the Carousel width as other components in a Carousel act correctly.

**Additional infofmation:**
 - Type: Simulator, Expo, Snack, Real device
 - Device: Android
 - OS: Any
 - Package version [e.g. 1.0.0]: 1.5.7
 - Expo version (in `app.json`): 36.0.0
 - Expo CLI version: 3.13.1

**Additional context**
Source: https://github.com/kevgrig/testvideo/blob/master/App.js
Carousel: https://github.com/archriss/react-native-snap-carousel

**Screenshots** (if applicable)
![Screenshot_20200223_195613-1](https://user-images.githubusercontent.com/6432587/75127985-cfc2c800-5676-11ea-9817-2eb568112dc7.png)

**Comment by ihmpavel** [comment]
Hi, 

you are passing `width`, `height` props to `videoProps` object.

You should be passing them straight to main `Video` object.

```
<VideoPlayer
  width={(viewportWidth * .8) - 5}
  height={viewportHeight}
  videoProps={...}
/>
```

**Comment by kevgrig** [comment]
That fixed it, thanks!
