### ISSUE TITLE
iOS: Sporadically, video doesn't load with infinite spinner (iPhone SE) or NSURLErrorDomain error

### ISSUE THREAD

**Issue by kevgrig** [ihmpavel/expo-video-player#71]
**Describe the bug**
iOS: Sporadically, video doesn't load with infinite spinner (iPhone SE) or NSURLErrorDomain error

**To Reproduce**
1. https://snack.expo.io/@git/github.com/kevgrig/testvideo
2. Open on iOS
3. Sometimes, the video shows an error with NSURLErrorDomain

**Expected behavior**
Video always loads as on Android.

**Additional infofmation:**
 - Type: Simulator, Expo, Snack, Real device
 - Device: iOS
 - OS: Any
 - Package version [e.g. 1.0.0]: 1.5.7
 - Expo version (in `app.json`): 36.0.0
 - Expo CLI version: 3.13.1

**Additional context**
Source: https://github.com/kevgrig/testvideo/blob/master/App.js
Carousel: https://github.com/archriss/react-native-snap-carousel

**Screenshots** (if applicable)
![Screenshot_20200223_200358](https://user-images.githubusercontent.com/6432587/75128267-1f55c380-5678-11ea-9440-84cebfcaf1b5.png)
![Screenshot 2020-02-23 at 8 02 37 PM](https://user-images.githubusercontent.com/6432587/75128288-38f70b00-5678-11ea-866e-834128a95de3.png)

**Comment by kevgrig** [comment]
Another error seen on iPhone SE:

```
Error: , Encountered a fatal error during playback: The server is not correctly configured. - The AVPlayerItem instance has failed with the error code -11850 and domain "AVFoundationErrorDomain"., Fatal, Object {}
- node_modules/expo/build/environment/muteWarnings.fx.js:27:24 in error
- node_modules/expo-video-player/dist/index.js:70:19 in defaultProps.errorCallback
- node_modules/expo-video-player/dist/index.js:161:25 in updatePlaybackCallback
- node_modules/expo-av/build/Video.js:56:27 in _handleNewStatus
* http://packager.k5-i8w.kevg.drom-react-native.exp.direct/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:174223:31 in <unknown>
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:307:15 in invokeGuardedCallbackImpl
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:531:36 in invokeGuardedCallback
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:555:30 in invokeGuardedCallbackAndCatchFirstError
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:722:42 in executeDispatch
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:744:20 in executeDispatchesInOrder
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:907:29 in executeDispatchesAndRelease
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:889:12 in forEachAccumulated
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:932:21 in runEventsInBatch
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:1096:19 in runExtractedPluginEventsInBatch
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:2796:6 in batchedUpdates$argument_0
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:18791:14 in batchedUpdates$1
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:2709:30 in batchedUpdates
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:2794:17 in batchedUpdates$argument_0
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:2814:26 in receiveEvent
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:436:47 in __callFunction
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:111:26 in __guard$argument_0
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:384:10 in __guard
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:110:17 in __guard$argument_0
* [native code]:null in callFunctionReturnFlushedQueue
```

**Comment by ihmpavel** [comment]
Hi, this kind of error is pretty hard to detect & debug, because it is out of scope of this package (In RN/Expo core & this package is just UI library on top of default Video).

**Comment by kevgrig** [comment]
Ok, I will open a bug in Expo.

**Comment by KaranChimple** [comment]
I'm facing this issue on iOS even on the latest version of expo-video-player. I have the video player running on the parent screen which lists a group of posts and when I click on that particular post with the video, the video from the parent screen continues to run and in the child screen, I get this error, "Encountered a fatal error during playback: The AVPlayerItem instance has failed with the error code -1008 and domain "NSURLErrorDomain".

**Comment by kevgrig** [comment]
@KaranChimple Sorry, but I don't have much to help with. I decided to create a custom video player component that directly interacts with <Video /> and the Video/Audio APIs and I don't have any issues, but it's complicated code.
