### ISSUE TITLE
iOS: Video width is greater than expected

### ISSUE THREAD

**Issue by kevgrig** [ihmpavel/expo-video-player#72]
**Describe the bug**
iOS: Video width is greater than expected. It should be 80% of the viewport width but it's more. Android works properly.

**To Reproduce**
1. https://snack.expo.io/@git/github.com/kevgrig/testvideo
2. Open on iOS
3. Observe width is greater than 80% of viewport width.

**Expected behavior**
Video always correct width as on Android.

**Additional infofmation:**
 - Type: Simulator, Expo, Snack, Real device
 - Device: iOS
 - OS: Any
 - Package version [e.g. 1.0.0]: 1.5.7
 - Expo version (in `app.json`): 36.0.0
 - Expo CLI version: 3.13.1

**Additional context**
Source: https://github.com/kevgrig/testvideo/blob/master/App.js
Carousel: https://github.com/archriss/react-native-snap-carousel

**Screenshots** (if applicable)
![Screenshot_20200223_201018](https://user-images.githubusercontent.com/6432587/75128366-9723ee00-5678-11ea-94f1-5a2556068b5f.png)

**Comment by ihmpavel** [comment]
Hi,

you are passing width, height props to videoProps object.

You should be passing them straight to main Video object.

<VideoPlayer
  width={(viewportWidth * .8) - 5}
  height={viewportHeight}
  videoProps={...}
/>

**Comment by kevgrig** [comment]
That worked, thanks!
